### PR TITLE
Synth instructions

### PR DESCRIPTION
**Pull request by jacobhylen**
Hey @tommaso1 ! 
I've included some assets that we want to use in this PR as well, where should they be stored to display properly?

### CODE REVIEW

**Comment by tommaso1** [comment]
You can host them on a public server -- something reachable via `https://some-url/some-file.png`
and then use the url of the file on the configuration file. 

Alternatively we can embed those assets directly on the public directory of the app. 
If we choose that path I'll deploy the assets alongside the application and you can reference them in the config file with just `some-file.png`

**Comment by jacobhylen** [comment]
Got it, thanks :)

**Comment by jacobhylen** [comment]
Hey @tommaso1 !
We'd like to have this deployed by the end of the day. I see that it's been split into many smaller files on the main branch.
If I rework my instructions to follow the same 5 file format, can we make that happen? 🤞

**Comment by karlsoderby** [comment]
Hey @tommaso1 are you able to merge this PR? We have a user testing in about 2 hours so we need to have the updated instructions. Thank you very much!

**Pull request merged**
